#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# bspc monitor -d I II III IV V VI VII VIII IX X

if [[ $(xrandr -q | grep "DP-3 connected") ]];
  then
    bspc monitor DP-3 -d I II III IV V VI VII VIII IX X
    bspc monitor DP-3 -s eDP-1
    xrandr --output DP-3 --primary -s 1920x1080
  else 
    bspc monitor eDP-1 -d I II III IV V VI VII VIII IX
fi

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Set wallpaper image tile
feh --bg-tile "$(< "${HOME}/.cache/wal/wal")"  

# Launch polybar themes
~/.config/polybar/launch.sh --material

# Retrieve pywal colors 
wal -R


